name: Build for GitHub Pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      
      # Install dependencies
      - name: Install dependencies
        run: yarn install
      
      # Build application to GitHub pages directory
      - name: Build
        run: yarn build
